version: '3.7'
services:
  telegrambot:
    image: pablokbs/pelade-transmission-bot
    restart: unless-stopped
    command: python /code/transmission_bot/telegram_bot.py
    environment:
      - ADDRESS=transmission #O IP transmission
      - PORT=9091
      - TS_USER=user #usuarioTranmsission
      - PASSWORD=password #passwordTranmsission
      - TOKEN=IDChat:Token #ID y Token Bot Telegram
      - PERSISTENCE_FILE=/var/lib/transmission-telegram/authorized_chats
